// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package components

import (
	"github.com/DaanV2/mechanus/server/pkg/config"
	"github.com/DaanV2/mechanus/server/pkg/models"
	"github.com/DaanV2/mechanus/server/pkg/storage"
	"github.com/DaanV2/mechanus/server/pkg/storage/files"
	"github.com/DaanV2/mechanus/server/services/users"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewUserService() *users.Service {
	userConfig := config.GetUserConfig()
	storage := newUserStorage(userConfig)
	service := users.NewService(storage)
	return service
}

// wire.go:

var (
	configSet  = wire.NewSet(config.GetUserConfig)
	storageSet = wire.NewSet(
		newUserStorage,
	)
)

// Storage
func newUserStorage(conf config.UserConfig) storage.Storage[models.User] {
	return file_storage.NewStorage[models.User](conf.CacheDir)
}
