// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file screens/v1/client.proto (package screens.v1, syntax proto3)
 

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Ping } from "./general_pb";
import { file_screens_v1_general } from "./general_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file screens/v1/client.proto.
 */
export const file_screens_v1_client: GenFile = /*@__PURE__*/
  fileDesc("ChdzY3JlZW5zL3YxL2NsaWVudC5wcm90bxIKc2NyZWVucy52MSI7Cg5DbGllbnRNZXNzYWdlcxIpCgZhY3Rpb24YASADKAsyGS5zY3JlZW5zLnYxLkNsaWVudE1lc3NhZ2UilQEKDUNsaWVudE1lc3NhZ2USDwoCaWQYASABKAlIAYgBARJAChVpbml0aWFsX3NldHVwX3JlcXVlc3QYAiABKAsyHy5zY3JlZW5zLnYxLkluaXRpYWxTZXR1cFJlcXVlc3RIABIgCgRwaW5nGAMgASgLMhAuc2NyZWVucy52MS5QaW5nSABCCAoGYWN0aW9uQgUKA19pZCIVChNJbml0aWFsU2V0dXBSZXF1ZXN0QkZaRGdpdGh1Yi5jb20vRGFhblYyL21lY2hhbnVzL3NlcnZlci9wa2cvZ2VuL3Byb3RvL3NjcmVlbnMvdjE7c2NyZWVuc3YxYgZwcm90bzM", [file_screens_v1_general]);

/**
 * @generated from message screens.v1.ClientMessages
 */
export type ClientMessages = Message<"screens.v1.ClientMessages"> & {
  /**
   * @generated from field: repeated screens.v1.ClientMessage action = 1;
   */
  action: ClientMessage[];
};

/**
 * Describes the message screens.v1.ClientMessages.
 * Use `create(ClientMessagesSchema)` to create a new message.
 */
export const ClientMessagesSchema: GenMessage<ClientMessages> = /*@__PURE__*/
  messageDesc(file_screens_v1_client, 0);

/**
 * @generated from message screens.v1.ClientMessage
 */
export type ClientMessage = Message<"screens.v1.ClientMessage"> & {
  /**
   * Unique identifier for the message, in case request <-> response matching is needed.
   *
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from oneof screens.v1.ClientMessage.action
   */
  action: {
    /**
     * @generated from field: screens.v1.InitialSetupRequest initial_setup_request = 2;
     */
    value: InitialSetupRequest;
    case: "initialSetupRequest";
  } | {
    /**
     * @generated from field: screens.v1.Ping ping = 3;
     */
    value: Ping;
    case: "ping";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message screens.v1.ClientMessage.
 * Use `create(ClientMessageSchema)` to create a new message.
 */
export const ClientMessageSchema: GenMessage<ClientMessage> = /*@__PURE__*/
  messageDesc(file_screens_v1_client, 1);

/**
 * @generated from message screens.v1.InitialSetupRequest
 */
export type InitialSetupRequest = Message<"screens.v1.InitialSetupRequest"> & {
};

/**
 * Describes the message screens.v1.InitialSetupRequest.
 * Use `create(InitialSetupRequestSchema)` to create a new message.
 */
export const InitialSetupRequestSchema: GenMessage<InitialSetupRequest> = /*@__PURE__*/
  messageDesc(file_screens_v1_client, 2);

