// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file screens/v1/general.proto (package screens.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file screens/v1/general.proto.
 */
export const file_screens_v1_general: GenFile = /*@__PURE__*/
  fileDesc("ChhzY3JlZW5zL3YxL2dlbmVyYWwucHJvdG8SCnNjcmVlbnMudjEiMgoEUGluZxIJCgF4GAEgASgCEgkKAXkYAiABKAISFAoMaW5pdGlhdG9yX2lkGAMgASgJQkZaRGdpdGh1Yi5jb20vRGFhblYyL21lY2hhbnVzL3NlcnZlci9wa2cvZ2VuL3Byb3RvL3NjcmVlbnMvdjE7c2NyZWVuc3YxYgZwcm90bzM");

/**
 * @generated from message screens.v1.Ping
 */
export type Ping = Message<"screens.v1.Ping"> & {
  /**
   * Coordinates
   *
   * @generated from field: float x = 1;
   */
  x: number;

  /**
   * Coordinates
   *
   * @generated from field: float y = 2;
   */
  y: number;

  /**
   * The player/device that initiated the ping
   *
   * @generated from field: string initiator_id = 3;
   */
  initiatorId: string;
};

/**
 * Describes the message screens.v1.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export const PingSchema: GenMessage<Ping> = /*@__PURE__*/
  messageDesc(file_screens_v1_general, 0);

