// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file screens/v1/scene_actions.proto (package screens.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file screens/v1/scene_actions.proto.
 */
export const file_screens_v1_scene_actions: GenFile = /*@__PURE__*/
  fileDesc("Ch5zY3JlZW5zL3YxL3NjZW5lX2FjdGlvbnMucHJvdG8SCnNjcmVlbnMudjEiGQoLU2NlbmVDaGFuZ2USCgoCaWQYASABKAkiFgoUU2NlbmVDaGFuZ2VDb21wbGV0ZWRCRlpEZ2l0aHViLmNvbS9EYWFuVjIvbWVjaGFudXMvc2VydmVyL3BrZy9nZW4vcHJvdG8vc2NyZWVucy92MTtzY3JlZW5zdjFiBnByb3RvMw");

/**
 * @generated from message screens.v1.SceneChange
 */
export type SceneChange = Message<"screens.v1.SceneChange"> & {
  /**
   * The id of the new scene to load
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message screens.v1.SceneChange.
 * Use `create(SceneChangeSchema)` to create a new message.
 */
export const SceneChangeSchema: GenMessage<SceneChange> = /*@__PURE__*/
  messageDesc(file_screens_v1_scene_actions, 0);

/**
 * Marks that the server thinks the scene load is complete
 *
 * @generated from message screens.v1.SceneChangeCompleted
 */
export type SceneChangeCompleted = Message<"screens.v1.SceneChangeCompleted"> & {
};

/**
 * Describes the message screens.v1.SceneChangeCompleted.
 * Use `create(SceneChangeCompletedSchema)` to create a new message.
 */
export const SceneChangeCompletedSchema: GenMessage<SceneChangeCompleted> = /*@__PURE__*/
  messageDesc(file_screens_v1_scene_actions, 1);

