// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file screens/v1/screens.proto (package screens.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ClientMessages } from "./client_pb.js";
import { ServerMessages } from "./server_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service screens.v1.ScreensService
 */
export const ScreensService = {
  typeName: "screens.v1.ScreensService",
  methods: {
    /**
     * @generated from rpc screens.v1.ScreensService.DuplexUpdates
     */
    duplexUpdates: {
      name: "DuplexUpdates",
      I: ClientMessages,
      O: ServerMessages,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

