// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file screens/v1/server.proto (package screens.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { SceneChange, SceneChangeCompleted } from "./scene_actions_pb";
import { file_screens_v1_scene_actions } from "./scene_actions_pb";
import type { SplashScreen } from "./splash_screen_pb";
import { file_screens_v1_splash_screen } from "./splash_screen_pb";
import type { Ping } from "./general_pb";
import { file_screens_v1_general } from "./general_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file screens/v1/server.proto.
 */
export const file_screens_v1_server: GenFile = /*@__PURE__*/
  fileDesc("ChdzY3JlZW5zL3YxL3NlcnZlci5wcm90bxIKc2NyZWVucy52MSI7Cg5TZXJ2ZXJNZXNzYWdlcxIpCgZhY3Rpb24YASADKAsyGS5zY3JlZW5zLnYxLlNlcnZlck1lc3NhZ2UiggIKDVNlcnZlck1lc3NhZ2USDwoCaWQYASABKAlIAYgBARI4ChRzcGxhc2hfc2NyZWVuX3VwZGF0ZRgCIAEoCzIYLnNjcmVlbnMudjEuU3BsYXNoU2NyZWVuSAASLwoMc2NlbmVfY2hhbmdlGAMgASgLMhcuc2NyZWVucy52MS5TY2VuZUNoYW5nZUgAEkIKFnNjZW5lX2NoYW5nZV9jb21wbGV0ZWQYBCABKAsyIC5zY3JlZW5zLnYxLlNjZW5lQ2hhbmdlQ29tcGxldGVkSAASIAoEcGluZxgFIAEoCzIQLnNjcmVlbnMudjEuUGluZ0gAQggKBmFjdGlvbkIFCgNfaWRCRlpEZ2l0aHViLmNvbS9EYWFuVjIvbWVjaGFudXMvc2VydmVyL3BrZy9nZW4vcHJvdG8vc2NyZWVucy92MTtzY3JlZW5zdjFiBnByb3RvMw", [file_screens_v1_scene_actions, file_screens_v1_splash_screen, file_screens_v1_general]);

/**
 * @generated from message screens.v1.ServerMessages
 */
export type ServerMessages = Message<"screens.v1.ServerMessages"> & {
  /**
   * @generated from field: repeated screens.v1.ServerMessage action = 1;
   */
  action: ServerMessage[];
};

/**
 * Describes the message screens.v1.ServerMessages.
 * Use `create(ServerMessagesSchema)` to create a new message.
 */
export const ServerMessagesSchema: GenMessage<ServerMessages> = /*@__PURE__*/
  messageDesc(file_screens_v1_server, 0);

/**
 * @generated from message screens.v1.ServerMessage
 */
export type ServerMessage = Message<"screens.v1.ServerMessage"> & {
  /**
   * Unique identifier for the message, in case request <-> response matching is needed.
   *
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from oneof screens.v1.ServerMessage.action
   */
  action: {
    /**
     * @generated from field: screens.v1.SplashScreen splash_screen_update = 2;
     */
    value: SplashScreen;
    case: "splashScreenUpdate";
  } | {
    /**
     * @generated from field: screens.v1.SceneChange scene_change = 3;
     */
    value: SceneChange;
    case: "sceneChange";
  } | {
    /**
     * @generated from field: screens.v1.SceneChangeCompleted scene_change_completed = 4;
     */
    value: SceneChangeCompleted;
    case: "sceneChangeCompleted";
  } | {
    /**
     * @generated from field: screens.v1.Ping ping = 5;
     */
    value: Ping;
    case: "ping";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message screens.v1.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema: GenMessage<ServerMessage> = /*@__PURE__*/
  messageDesc(file_screens_v1_server, 1);

