// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file screens/v1/setup.proto (package screens.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file screens/v1/setup.proto.
 */
export const file_screens_v1_setup: GenFile = /*@__PURE__*/
  fileDesc("ChZzY3JlZW5zL3YxL3NldHVwLnByb3RvEgpzY3JlZW5zLnYxIhUKE0luaXRpYWxTZXR1cFJlcXVlc3QiFgoUSW5pdGlhbFNldHVwUmVzcG9uc2VCRlpEZ2l0aHViLmNvbS9EYWFuVjIvbWVjaGFudXMvc2VydmVyL3BrZy9nZW4vcHJvdG8vc2NyZWVucy92MTtzY3JlZW5zdjFiBnByb3RvMw");

/**
 * @generated from message screens.v1.InitialSetupRequest
 */
export type InitialSetupRequest = Message<"screens.v1.InitialSetupRequest"> & {
};

/**
 * Describes the message screens.v1.InitialSetupRequest.
 * Use `create(InitialSetupRequestSchema)` to create a new message.
 */
export const InitialSetupRequestSchema: GenMessage<InitialSetupRequest> = /*@__PURE__*/
  messageDesc(file_screens_v1_setup, 0);

/**
 * @generated from message screens.v1.InitialSetupResponse
 */
export type InitialSetupResponse = Message<"screens.v1.InitialSetupResponse"> & {
};

/**
 * Describes the message screens.v1.InitialSetupResponse.
 * Use `create(InitialSetupResponseSchema)` to create a new message.
 */
export const InitialSetupResponseSchema: GenMessage<InitialSetupResponse> = /*@__PURE__*/
  messageDesc(file_screens_v1_setup, 1);

