// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file screens/v1/splash_screen.proto (package screens.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file screens/v1/splash_screen.proto.
 */
export const file_screens_v1_splash_screen: GenFile = /*@__PURE__*/
  fileDesc("Ch5zY3JlZW5zL3YxL3NwbGFzaF9zY3JlZW4ucHJvdG8SCnNjcmVlbnMudjEijgEKDFNwbGFzaFNjcmVlbhIMCgRzaG93GAEgASgIEhIKBXRpdGxlGAIgASgJSACIAQESFQoIc3VidGl0bGUYAyABKAlIAYgBARIbCg5iYWNrZ3JvdW5kX2hleBgEIAEoCUgCiAEBQggKBl90aXRsZUILCglfc3VidGl0bGVCEQoPX2JhY2tncm91bmRfaGV4QkZaRGdpdGh1Yi5jb20vRGFhblYyL21lY2hhbnVzL3NlcnZlci9wa2cvZ2VuL3Byb3RvL3NjcmVlbnMvdjE7c2NyZWVuc3YxYgZwcm90bzM");

/**
 * @generated from message screens.v1.SplashScreen
 */
export type SplashScreen = Message<"screens.v1.SplashScreen"> & {
  /**
   * @generated from field: bool show = 1;
   */
  show: boolean;

  /**
   * @generated from field: optional string title = 2;
   */
  title?: string;

  /**
   * @generated from field: optional string subtitle = 3;
   */
  subtitle?: string;

  /**
   * @generated from field: optional string background_hex = 4;
   */
  backgroundHex?: string;
};

/**
 * Describes the message screens.v1.SplashScreen.
 * Use `create(SplashScreenSchema)` to create a new message.
 */
export const SplashScreenSchema: GenMessage<SplashScreen> = /*@__PURE__*/
  messageDesc(file_screens_v1_splash_screen, 0);

