// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file screens/v1/state.proto (package screens.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { SplashScreen } from "./splash_screen_pb";
import { file_screens_v1_splash_screen } from "./splash_screen_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file screens/v1/state.proto.
 */
export const file_screens_v1_state: GenFile = /*@__PURE__*/
  fileDesc("ChZzY3JlZW5zL3YxL3N0YXRlLnByb3RvEgpzY3JlZW5zLnYxIs0BCgtTY3JlZW5TdGF0ZRIsCgtlbnZpcm9ubWVudBgBIAEoCzIXLnNjcmVlbnMudjEuRW52aXJvbm1lbnQSJgoEZ3JpZBgCIAEoCzIYLnNjcmVlbnMudjEuR3JpZFNldHRpbmdzEiAKBWxheWVyGAMgAygLMhEuc2NyZWVucy52MS5MYXllchI0Cg1zcGxhc2hfc2NyZWVuGBQgASgLMhguc2NyZWVucy52MS5TcGxhc2hTY3JlZW5IAIgBAUIQCg5fc3BsYXNoX3NjcmVlbiJyCgtFbnZpcm9ubWVudBIwCgxjdXJyZW50X3RpbWUYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhgKEGJhY2tncm91bmRfY29sb3IYAiABKAkSFwoPbGlnaHRfaW50ZW5zaXR5GAMgASgBIlQKDEdyaWRTZXR0aW5ncxIQCgh4X29mZnNldBgBIAEoBRIQCgh5X29mZnNldBgCIAEoBRIPCgd4X3JhdGlvGAMgASgFEg8KB3lfcmF0aW8YBCABKAUiKwoFTGF5ZXISIgoGZW50aXR5GAEgAygLMhIuc2NyZWVucy52MS5FbnRpdHkikwEKBkVudGl0eRIKCgJpZBgBIAEoCRIgCgVhc3NldBgCIAEoCzIRLnNjcmVlbnMudjEuQXNzZXQSJQoIcG9zaXRpb24YAyABKAsyEy5zY3JlZW5zLnYxLlZlY3RvcjISIgoFc2NhbGUYBCABKAsyEy5zY3JlZW5zLnYxLlZlY3RvcjISEAoIcm90YXRpb24YBSABKAEiIgoFQXNzZXQSDAoEbmFtZRgBIAEoCRILCgN1cmwYAiABKAkiHwoHVmVjdG9yMhIJCgF4GAEgASgBEgkKAXkYAiABKAFCRlpEZ2l0aHViLmNvbS9EYWFuVjIvbWVjaGFudXMvc2VydmVyL3BrZy9nZW4vcHJvdG8vc2NyZWVucy92MTtzY3JlZW5zdjFiBnByb3RvMw", [file_google_protobuf_timestamp, file_screens_v1_splash_screen]);

/**
 * @generated from message screens.v1.ScreenState
 */
export type ScreenState = Message<"screens.v1.ScreenState"> & {
  /**
   * @generated from field: screens.v1.Environment environment = 1;
   */
  environment?: Environment;

  /**
   * @generated from field: screens.v1.GridSettings grid = 2;
   */
  grid?: GridSettings;

  /**
   * @generated from field: repeated screens.v1.Layer layer = 3;
   */
  layer: Layer[];

  /**
   * @generated from field: optional screens.v1.SplashScreen splash_screen = 20;
   */
  splashScreen?: SplashScreen;
};

/**
 * Describes the message screens.v1.ScreenState.
 * Use `create(ScreenStateSchema)` to create a new message.
 */
export const ScreenStateSchema: GenMessage<ScreenState> = /*@__PURE__*/
  messageDesc(file_screens_v1_state, 0);

/**
 * @generated from message screens.v1.Environment
 */
export type Environment = Message<"screens.v1.Environment"> & {
  /**
   * @generated from field: google.protobuf.Timestamp current_time = 1;
   */
  currentTime?: Timestamp;

  /**
   * @generated from field: string background_color = 2;
   */
  backgroundColor: string;

  /**
   * @generated from field: double light_intensity = 3;
   */
  lightIntensity: number;
};

/**
 * Describes the message screens.v1.Environment.
 * Use `create(EnvironmentSchema)` to create a new message.
 */
export const EnvironmentSchema: GenMessage<Environment> = /*@__PURE__*/
  messageDesc(file_screens_v1_state, 1);

/**
 * @generated from message screens.v1.GridSettings
 */
export type GridSettings = Message<"screens.v1.GridSettings"> & {
  /**
   * @generated from field: int32 x_offset = 1;
   */
  xOffset: number;

  /**
   * @generated from field: int32 y_offset = 2;
   */
  yOffset: number;

  /**
   * @generated from field: int32 x_ratio = 3;
   */
  xRatio: number;

  /**
   * @generated from field: int32 y_ratio = 4;
   */
  yRatio: number;
};

/**
 * Describes the message screens.v1.GridSettings.
 * Use `create(GridSettingsSchema)` to create a new message.
 */
export const GridSettingsSchema: GenMessage<GridSettings> = /*@__PURE__*/
  messageDesc(file_screens_v1_state, 2);

/**
 * @generated from message screens.v1.Layer
 */
export type Layer = Message<"screens.v1.Layer"> & {
  /**
   * @generated from field: repeated screens.v1.Entity entity = 1;
   */
  entity: Entity[];
};

/**
 * Describes the message screens.v1.Layer.
 * Use `create(LayerSchema)` to create a new message.
 */
export const LayerSchema: GenMessage<Layer> = /*@__PURE__*/
  messageDesc(file_screens_v1_state, 3);

/**
 * @generated from message screens.v1.Entity
 */
export type Entity = Message<"screens.v1.Entity"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: screens.v1.Asset asset = 2;
   */
  asset?: Asset;

  /**
   * @generated from field: screens.v1.Vector2 position = 3;
   */
  position?: Vector2;

  /**
   * @generated from field: screens.v1.Vector2 scale = 4;
   */
  scale?: Vector2;

  /**
   * @generated from field: double rotation = 5;
   */
  rotation: number;
};

/**
 * Describes the message screens.v1.Entity.
 * Use `create(EntitySchema)` to create a new message.
 */
export const EntitySchema: GenMessage<Entity> = /*@__PURE__*/
  messageDesc(file_screens_v1_state, 4);

/**
 * @generated from message screens.v1.Asset
 */
export type Asset = Message<"screens.v1.Asset"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string url = 2;
   */
  url: string;
};

/**
 * Describes the message screens.v1.Asset.
 * Use `create(AssetSchema)` to create a new message.
 */
export const AssetSchema: GenMessage<Asset> = /*@__PURE__*/
  messageDesc(file_screens_v1_state, 5);

/**
 * @generated from message screens.v1.Vector2
 */
export type Vector2 = Message<"screens.v1.Vector2"> & {
  /**
   * @generated from field: double x = 1;
   */
  x: number;

  /**
   * @generated from field: double y = 2;
   */
  y: number;
};

/**
 * Describes the message screens.v1.Vector2.
 * Use `create(Vector2Schema)` to create a new message.
 */
export const Vector2Schema: GenMessage<Vector2> = /*@__PURE__*/
  messageDesc(file_screens_v1_state, 6);

