// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: shared/proto/v1/campaign.proto

package grpc_v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// CampaignClient is the client API for Campaign service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CampaignClient interface {
}

type campaignClient struct {
	cc grpc.ClientConnInterface
}

func NewCampaignClient(cc grpc.ClientConnInterface) CampaignClient {
	return &campaignClient{cc}
}

// CampaignServer is the server API for Campaign service.
// All implementations must embed UnimplementedCampaignServer
// for forward compatibility.
type CampaignServer interface {
	mustEmbedUnimplementedCampaignServer()
}

// UnimplementedCampaignServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCampaignServer struct{}

func (UnimplementedCampaignServer) mustEmbedUnimplementedCampaignServer() {}
func (UnimplementedCampaignServer) testEmbeddedByValue()                  {}

// UnsafeCampaignServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CampaignServer will
// result in compilation errors.
type UnsafeCampaignServer interface {
	mustEmbedUnimplementedCampaignServer()
}

func RegisterCampaignServer(s grpc.ServiceRegistrar, srv CampaignServer) {
	// If the following call pancis, it indicates UnimplementedCampaignServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Campaign_ServiceDesc, srv)
}

// Campaign_ServiceDesc is the grpc.ServiceDesc for Campaign service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Campaign_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Campaign",
	HandlerType: (*CampaignServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "shared/proto/v1/campaign.proto",
}
