// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: shared/proto/v1/rendering.proto

package grpc_v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// RenderingClient is the client API for Rendering service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RenderingClient interface {
}

type renderingClient struct {
	cc grpc.ClientConnInterface
}

func NewRenderingClient(cc grpc.ClientConnInterface) RenderingClient {
	return &renderingClient{cc}
}

// RenderingServer is the server API for Rendering service.
// All implementations must embed UnimplementedRenderingServer
// for forward compatibility.
type RenderingServer interface {
	mustEmbedUnimplementedRenderingServer()
}

// UnimplementedRenderingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRenderingServer struct{}

func (UnimplementedRenderingServer) mustEmbedUnimplementedRenderingServer() {}
func (UnimplementedRenderingServer) testEmbeddedByValue()                   {}

// UnsafeRenderingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RenderingServer will
// result in compilation errors.
type UnsafeRenderingServer interface {
	mustEmbedUnimplementedRenderingServer()
}

func RegisterRenderingServer(s grpc.ServiceRegistrar, srv RenderingServer) {
	// If the following call pancis, it indicates UnimplementedRenderingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rendering_ServiceDesc, srv)
}

// Rendering_ServiceDesc is the grpc.ServiceDesc for Rendering service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rendering_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Rendering",
	HandlerType: (*RenderingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "shared/proto/v1/rendering.proto",
}
