// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file rendering/v1/rendering.proto (package rendering.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from service rendering.v1.RenderingService
 */
export const RenderingService = {
  typeName: "rendering.v1.RenderingService",
  methods: {
  }
} as const;

