// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file rendering/v1/rendering.proto (package rendering.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file rendering/v1/rendering.proto.
 */
export const file_rendering_v1_rendering: GenFile = /*@__PURE__*/
  fileDesc("ChxyZW5kZXJpbmcvdjEvcmVuZGVyaW5nLnByb3RvEgxyZW5kZXJpbmcudjEyEgoQUmVuZGVyaW5nU2VydmljZUJKWkhnaXRodWIuY29tL0RhYW5WMi9tZWNoYW51cy9zZXJ2ZXIvaW50ZXJuYWwvZ3JwYy9yZW5kZXJpbmcvdjE7cmVuZGVyaW5ndjFiBnByb3RvMw");

/**
 * @generated from service rendering.v1.RenderingService
 */
export const RenderingService: GenService<{
}> = /*@__PURE__*/
  serviceDesc(file_rendering_v1_rendering, 0);

