// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file users/v1/login.proto (package users.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateAccountRequest, CreateAccountResponse, LoginRequest, LoginResponse, RefreshTokenRequest, RefreshTokenResponse } from "./login_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * A service for logging in a user, or creating their account
 *
 * @generated from service users.v1.LoginService
 */
export const LoginService = {
  typeName: "users.v1.LoginService",
  methods: {
    /**
     * Log in the user, returns a JWT token
     *
     * @generated from rpc users.v1.LoginService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Create a new user, returns a JWT token
     *
     * @generated from rpc users.v1.LoginService.Create
     */
    create: {
      name: "Create",
      I: CreateAccountRequest,
      O: CreateAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Refresh a given token, with a new JWT token
     *
     * @generated from rpc users.v1.LoginService.Refresh
     */
    refresh: {
      name: "Refresh",
      I: RefreshTokenRequest,
      O: RefreshTokenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

