// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file users/v1/login.proto (package users.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file users/v1/login.proto.
 */
export const file_users_v1_login: GenFile = /*@__PURE__*/
  fileDesc("ChR1c2Vycy92MS9sb2dpbi5wcm90bxIIdXNlcnMudjEiMgoMTG9naW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIiwKDUxvZ2luUmVzcG9uc2USDQoFdG9rZW4YASABKAkSDAoEdHlwZRgCIAEoCSIkChNSZWZyZXNoVG9rZW5SZXF1ZXN0Eg0KBXRva2VuGAEgASgJIjMKFFJlZnJlc2hUb2tlblJlc3BvbnNlEg0KBXRva2VuGAEgASgJEgwKBHR5cGUYAiABKAkylgEKDExvZ2luU2VydmljZRI6CgVMb2dpbhIWLnVzZXJzLnYxLkxvZ2luUmVxdWVzdBoXLnVzZXJzLnYxLkxvZ2luUmVzcG9uc2UiABJKCgdSZWZyZXNoEh0udXNlcnMudjEuUmVmcmVzaFRva2VuUmVxdWVzdBoeLnVzZXJzLnYxLlJlZnJlc2hUb2tlblJlc3BvbnNlIgBCQlpAZ2l0aHViLmNvbS9EYWFuVjIvbWVjaGFudXMvc2VydmVyL3BrZy9nZW4vcHJvdG8vdXNlcnMvdjE7dXNlcnN2MWIGcHJvdG8z");

/**
 * A login request
 *
 * @generated from message users.v1.LoginRequest
 */
export type LoginRequest = Message<"users.v1.LoginRequest"> & {
  /**
   * The username
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * The password
   *
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message users.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_users_v1_login, 0);

/**
 * @generated from message users.v1.LoginResponse
 */
export type LoginResponse = Message<"users.v1.LoginResponse"> & {
  /**
   * The JWT token, without prefix
   *
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * The prefix to be used, so far always Bearer
   *
   * @generated from field: string type = 2;
   */
  type: string;
};

/**
 * Describes the message users.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_users_v1_login, 1);

/**
 * @generated from message users.v1.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"users.v1.RefreshTokenRequest"> & {
  /**
   * The JWT token, without prefix
   *
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message users.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_users_v1_login, 2);

/**
 * @generated from message users.v1.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<"users.v1.RefreshTokenResponse"> & {
  /**
   * The JWT token, without prefix
   *
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * The prefix to be used, so far always Bearer
   *
   * @generated from field: string type = 2;
   */
  type: string;
};

/**
 * Describes the message users.v1.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse> = /*@__PURE__*/
  messageDesc(file_users_v1_login, 3);

/**
 * A service for logging in a user, or creating their account
 *
 * @generated from service users.v1.LoginService
 */
export const LoginService: GenService<{
  /**
   * Log in the user, returns a JWT token
   *
   * @generated from rpc users.v1.LoginService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Refresh a given token, with a new JWT token
   *
   * @generated from rpc users.v1.LoginService.Refresh
   */
  refresh: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof RefreshTokenResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_users_v1_login, 0);

