// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file users/v1/users.proto (package users.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file users/v1/users.proto.
 */
export const file_users_v1_users: GenFile = /*@__PURE__*/
  fileDesc("ChR1c2Vycy92MS91c2Vycy5wcm90bxIIdXNlcnMudjEiOgoUQ3JlYXRlQWNjb3VudFJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiNQoVQ3JlYXRlQWNjb3VudFJlc3BvbnNlEhwKBHVzZXIYASABKAsyDi51c2Vycy52MS5Vc2VyIhwKDkdldFVzZXJSZXF1ZXN0EgoKAmlkGAEgASgJIi8KD0dldFVzZXJSZXNwb25zZRIcCgR1c2VyGAEgASgLMg4udXNlcnMudjEuVXNlciIgCgRVc2VyEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkymAEKC1VzZXJTZXJ2aWNlEksKBkNyZWF0ZRIeLnVzZXJzLnYxLkNyZWF0ZUFjY291bnRSZXF1ZXN0Gh8udXNlcnMudjEuQ3JlYXRlQWNjb3VudFJlc3BvbnNlIgASPAoDR2V0EhgudXNlcnMudjEuR2V0VXNlclJlcXVlc3QaGS51c2Vycy52MS5HZXRVc2VyUmVzcG9uc2UiAEI6WjhnaXRodWIuY29tL0RhYW5WMi9tZWNoYW51cy9zZXJ2ZXIvcHJvdG8vdXNlcnMvdjE7dXNlcnN2MWIGcHJvdG8z");

/**
 * @generated from message users.v1.CreateAccountRequest
 */
export type CreateAccountRequest = Message<"users.v1.CreateAccountRequest"> & {
  /**
   * The username
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * The password
   *
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message users.v1.CreateAccountRequest.
 * Use `create(CreateAccountRequestSchema)` to create a new message.
 */
export const CreateAccountRequestSchema: GenMessage<CreateAccountRequest> = /*@__PURE__*/
  messageDesc(file_users_v1_users, 0);

/**
 * @generated from message users.v1.CreateAccountResponse
 */
export type CreateAccountResponse = Message<"users.v1.CreateAccountResponse"> & {
  /**
   * @generated from field: users.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message users.v1.CreateAccountResponse.
 * Use `create(CreateAccountResponseSchema)` to create a new message.
 */
export const CreateAccountResponseSchema: GenMessage<CreateAccountResponse> = /*@__PURE__*/
  messageDesc(file_users_v1_users, 1);

/**
 * @generated from message users.v1.GetUserRequest
 */
export type GetUserRequest = Message<"users.v1.GetUserRequest"> & {
  /**
   * The users UUID to lookup
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message users.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_users_v1_users, 2);

/**
 * @generated from message users.v1.GetUserResponse
 */
export type GetUserResponse = Message<"users.v1.GetUserResponse"> & {
  /**
   * @generated from field: users.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message users.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_users_v1_users, 3);

/**
 * @generated from message users.v1.User
 */
export type User = Message<"users.v1.User"> & {
  /**
   * The users UUID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The users name
   *
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message users.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_users_v1_users, 4);

/**
 * @generated from service users.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc users.v1.UserService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateAccountRequestSchema;
    output: typeof CreateAccountResponseSchema;
  },
  /**
   * @generated from rpc users.v1.UserService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_users_v1_users, 0);

