// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file campaigns/v1/campaign.proto (package campaigns.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from service campaigns.v1.CampaignService
 */
export const CampaignService = {
  typeName: "campaigns.v1.CampaignService",
  methods: {
  }
} as const;

