// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file campaigns/v1/campaign.proto (package campaigns.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file campaigns/v1/campaign.proto.
 */
export const file_campaigns_v1_campaign: GenFile = /*@__PURE__*/
  fileDesc("ChtjYW1wYWlnbnMvdjEvY2FtcGFpZ24ucHJvdG8SDGNhbXBhaWducy52MTIRCg9DYW1wYWlnblNlcnZpY2VCSlpIZ2l0aHViLmNvbS9EYWFuVjIvbWVjaGFudXMvc2VydmVyL2ludGVybmFsL2dycGMvY2FtcGFpZ25zL3YxO2NhbXBhaWduc3YxYgZwcm90bzM");

/**
 * @generated from service campaigns.v1.CampaignService
 */
export const CampaignService: GenService<{
}> = /*@__PURE__*/
  serviceDesc(file_campaigns_v1_campaign, 0);

