name: Auto Label PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Label issues
      uses: actions/labeler@v5
