# This is a basic workflow to help you get started with Actions
name: 🖼️ Client
env:
  FORCE_COLOR: true

on:
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    name: 📋 Checks ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v7

      - name: ⚒️ Setup Node.js Environment
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: client/package-lock.json
          node-version-file: client/package.json

      - name: ⚒️ Setup Project
        working-directory: client
        run: npm ci

      - name: 🛠️ Compile
        working-directory: client
        run: npm run build

      - name: 📋 Test
        working-directory: client
        run: npm run test

      - name: 🔍 Linting
        working-directory: client
        run: npm run lint

      - name: 📝 Reporting
        run: |
          echo "✅ Client - ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY

