name: 🎭 Integration tests
on:
  workflow_call:
  workflow_dispatch:
env:
  CI: "true"
  FORCE_COLOR: true

jobs:
  test:
    name: 🎭 Integration tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚒️ Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: tests/package-lock.json
          node-version-file: tests/package.json

      - name: ⚒️ Install dependencies
        working-directory: tests
        run: npm ci

      - name: 🐋 Make server
        run: |
          make image

      - name: 🐋 Start server
        working-directory: tests
        run: |
          make server

      - name: 🎭 Run Playwright tests
        working-directory: tests
        run: npm run test

      - uses: actions/upload-artifact@v4
        if: ${{ !always() }}
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 10
