name: 🗃️ Proto
on:
  workflow_call:
  workflow_dispatch:

jobs:
  proto:
    name: 📋 Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v7

      - name: 🗃️ Proto checks
        uses: bufbuild/buf-action@v1
        with:
          setup_only: false
          format: true
          lint: true
          breaking: false
          push: false
