# This is a basic workflow to help you get started with Actions
name: 🗄️ Server
env:
  FORCE_COLOR: true

on:
  workflow_call:
  workflow_dispatch:

jobs:
  server-checks:
    name: 📋 Checks ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v7

      - name: ⚒️  Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: ./server/go.mod
          cache-dependency-path: ./server/go.sum

      - name: 🛠️ Build
        working-directory: server
        run: |
          go build ./...

      - name: 📋 Run Tests
        working-directory: server
        run: |
          go tool ginkgo run --output-dir reports --cover --covermode atomic -coverprofile=coverage.out ./...

      - name: 🔍 Run linting
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          working-directory: server

      - name: 📝 Reporting
        run: |
          echo "✅ Server - ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
