// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: screens/v1/setup.proto

package screensv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitialSetupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitialSetupRequest) Reset() {
	*x = InitialSetupRequest{}
	mi := &file_screens_v1_setup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSetupRequest) ProtoMessage() {}

func (x *InitialSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_screens_v1_setup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSetupRequest.ProtoReflect.Descriptor instead.
func (*InitialSetupRequest) Descriptor() ([]byte, []int) {
	return file_screens_v1_setup_proto_rawDescGZIP(), []int{0}
}

type InitialSetupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitialSetupResponse) Reset() {
	*x = InitialSetupResponse{}
	mi := &file_screens_v1_setup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSetupResponse) ProtoMessage() {}

func (x *InitialSetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_screens_v1_setup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSetupResponse.ProtoReflect.Descriptor instead.
func (*InitialSetupResponse) Descriptor() ([]byte, []int) {
	return file_screens_v1_setup_proto_rawDescGZIP(), []int{1}
}

var File_screens_v1_setup_proto protoreflect.FileDescriptor

var file_screens_v1_setup_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x74,
	0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x73, 0x2e, 0x76, 0x31, 0x22, 0x15, 0x0a, 0x13, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x44, 0x61, 0x61, 0x6e, 0x56, 0x32, 0x2f, 0x6d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x75,
	0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x2f, 0x76,
	0x31, 0x3b, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_screens_v1_setup_proto_rawDescOnce sync.Once
	file_screens_v1_setup_proto_rawDescData = file_screens_v1_setup_proto_rawDesc
)

func file_screens_v1_setup_proto_rawDescGZIP() []byte {
	file_screens_v1_setup_proto_rawDescOnce.Do(func() {
		file_screens_v1_setup_proto_rawDescData = protoimpl.X.CompressGZIP(file_screens_v1_setup_proto_rawDescData)
	})
	return file_screens_v1_setup_proto_rawDescData
}

var file_screens_v1_setup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_screens_v1_setup_proto_goTypes = []any{
	(*InitialSetupRequest)(nil),  // 0: screens.v1.InitialSetupRequest
	(*InitialSetupResponse)(nil), // 1: screens.v1.InitialSetupResponse
}
var file_screens_v1_setup_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_screens_v1_setup_proto_init() }
func file_screens_v1_setup_proto_init() {
	if File_screens_v1_setup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_screens_v1_setup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_screens_v1_setup_proto_goTypes,
		DependencyIndexes: file_screens_v1_setup_proto_depIdxs,
		MessageInfos:      file_screens_v1_setup_proto_msgTypes,
	}.Build()
	File_screens_v1_setup_proto = out.File
	file_screens_v1_setup_proto_rawDesc = nil
	file_screens_v1_setup_proto_goTypes = nil
	file_screens_v1_setup_proto_depIdxs = nil
}
