// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: screens/v1/splash_screen.proto

package screensv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SplashScreen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Show          bool    `protobuf:"varint,1,opt,name=show,proto3" json:"show,omitempty"`
	Title         *string `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Subtitle      *string `protobuf:"bytes,3,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	BackgroundHex *string `protobuf:"bytes,4,opt,name=background_hex,json=backgroundHex,proto3,oneof" json:"background_hex,omitempty"`
}

func (x *SplashScreen) Reset() {
	*x = SplashScreen{}
	mi := &file_screens_v1_splash_screen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplashScreen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplashScreen) ProtoMessage() {}

func (x *SplashScreen) ProtoReflect() protoreflect.Message {
	mi := &file_screens_v1_splash_screen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplashScreen.ProtoReflect.Descriptor instead.
func (*SplashScreen) Descriptor() ([]byte, []int) {
	return file_screens_v1_splash_screen_proto_rawDescGZIP(), []int{0}
}

func (x *SplashScreen) GetShow() bool {
	if x != nil {
		return x.Show
	}
	return false
}

func (x *SplashScreen) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *SplashScreen) GetSubtitle() string {
	if x != nil && x.Subtitle != nil {
		return *x.Subtitle
	}
	return ""
}

func (x *SplashScreen) GetBackgroundHex() string {
	if x != nil && x.BackgroundHex != nil {
		return *x.BackgroundHex
	}
	return ""
}

var File_screens_v1_splash_screen_proto protoreflect.FileDescriptor

var file_screens_v1_splash_screen_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x70, 0x6c,
	0x61, 0x73, 0x68, 0x5f, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xb4, 0x01, 0x0a,
	0x0c, 0x53, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x68, 0x6f,
	0x77, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08,
	0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a,
	0x0e, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x68, 0x65, 0x78, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x48, 0x65, 0x78, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f,
	0x68, 0x65, 0x78, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x44, 0x61, 0x61, 0x6e, 0x56, 0x32, 0x2f, 0x6d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x75,
	0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_screens_v1_splash_screen_proto_rawDescOnce sync.Once
	file_screens_v1_splash_screen_proto_rawDescData = file_screens_v1_splash_screen_proto_rawDesc
)

func file_screens_v1_splash_screen_proto_rawDescGZIP() []byte {
	file_screens_v1_splash_screen_proto_rawDescOnce.Do(func() {
		file_screens_v1_splash_screen_proto_rawDescData = protoimpl.X.CompressGZIP(file_screens_v1_splash_screen_proto_rawDescData)
	})
	return file_screens_v1_splash_screen_proto_rawDescData
}

var file_screens_v1_splash_screen_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_screens_v1_splash_screen_proto_goTypes = []any{
	(*SplashScreen)(nil), // 0: screens.v1.SplashScreen
}
var file_screens_v1_splash_screen_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_screens_v1_splash_screen_proto_init() }
func file_screens_v1_splash_screen_proto_init() {
	if File_screens_v1_splash_screen_proto != nil {
		return
	}
	file_screens_v1_splash_screen_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_screens_v1_splash_screen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_screens_v1_splash_screen_proto_goTypes,
		DependencyIndexes: file_screens_v1_splash_screen_proto_depIdxs,
		MessageInfos:      file_screens_v1_splash_screen_proto_msgTypes,
	}.Build()
	File_screens_v1_splash_screen_proto = out.File
	file_screens_v1_splash_screen_proto_rawDesc = nil
	file_screens_v1_splash_screen_proto_goTypes = nil
	file_screens_v1_splash_screen_proto_depIdxs = nil
}
